Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# experimentation code block

nodes = 100

X = np.random.uniform(.2, .8, size=(nodes, 2))
n1 = rdpg(X[:, 0, np.newaxis])
n2 = rdpg(X[:, 1, np.newaxis])

from graspologic.embed import OmnibusEmbed as OMNI
omni = OMNI(n_components=1)
latents = omni.fit_transform([n1, n2])

Xhat_1 = latents[0]
Xhat_2 = latents[1]

np.linalg.norm(Xhat_1 - Xhat_2, ord=2)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_1685/4265570678.py[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0mnodes[0m [0;34m=[0m [0;36m100[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[0;32m----> 5[0;31m [0mX[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mrandom[0m[0;34m.[0m[0muniform[0m[0;34m([0m[0;36m.2[0m[0;34m,[0m [0;36m.8[0m[0;34m,[0m [0msize[0m[0;34m=[0m[0;34m([0m[0mnodes[0m[0;34m,[0m [0;36m2[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m [0mn1[0m [0;34m=[0m [0mrdpg[0m[0;34m([0m[0mX[0m[0;34m[[0m[0;34m:[0m[0;34m,[0m [0;36m0[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mnewaxis[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0mn2[0m [0;34m=[0m [0mrdpg[0m[0;34m([0m[0mX[0m[0;34m[[0m[0;34m:[0m[0;34m,[0m [0;36m1[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mnewaxis[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

