Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import graspologic as gp

ns1 = 50; ns2 = 50
ns = [ns1, ns2]

# zvec is a column vector of 50 1s followed by 50 2s
# this vector gives the school each of the 100 students are from
zvec = np.array(["S1" for i in range(0, ns1)] + ["S2" for i in range(0, ns2)])

# the block matrix
B = [[0.5, 0.3], [0.3, 0.5]]

# the probability matrix
zvec_ohe = np.vstack([[1, 0] for i in range(0, ns1)] + [[0, 1] for i in range(0, ns2)])
P = zvec_ohe @ B @ zvec_ohe.transpose()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 8>[0;34m()[0m
[1;32m      4[0m ns [38;5;241m=[39m [ns1, ns2]
[1;32m      6[0m [38;5;66;03m# zvec is a column vector of 50 1s followed by 50 2s[39;00m
[1;32m      7[0m [38;5;66;03m# this vector gives the school each of the 100 students are from[39;00m
[0;32m----> 8[0m zvec [38;5;241m=[39m [43mnp[49m[38;5;241m.[39marray([[38;5;124m"[39m[38;5;124mS1[39m[38;5;124m"[39m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;241m0[39m, ns1)] [38;5;241m+[39m [[38;5;124m"[39m[38;5;124mS2[39m[38;5;124m"[39m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;241m0[39m, ns2)])
[1;32m     10[0m [38;5;66;03m# the block matrix[39;00m
[1;32m     11[0m B [38;5;241m=[39m [[[38;5;241m0.5[39m, [38;5;241m0.3[39m], [[38;5;241m0.3[39m, [38;5;241m0.5[39m]]

[0;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

