Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import networkx as nx

G = nx.DiGraph()
G.add_node("0", pos=(1,1))
G.add_node("1", pos=(4,4))
G.add_node("2", pos=(4,2))
G.add_edge("0", "1")
G.add_edge("1", "0")
G.add_edge("0", "2")
G.add_edge("2", "0")

pos = {'0': (0, 0), '1': (1, 0), '2': (.5, .5)}

nx.draw_networkx(G, with_labels=True, node_color="tab:purple", pos=pos,
                font_size=10, font_color="whitesmoke", arrows=False, edge_color="black",
                width=1)
A = np.asarray(nx.to_numpy_matrix(G))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[1], line 18[0m
[1;32m     13[0m pos [38;5;241m=[39m {[38;5;124m'[39m[38;5;124m0[39m[38;5;124m'[39m: ([38;5;241m0[39m, [38;5;241m0[39m), [38;5;124m'[39m[38;5;124m1[39m[38;5;124m'[39m: ([38;5;241m1[39m, [38;5;241m0[39m), [38;5;124m'[39m[38;5;124m2[39m[38;5;124m'[39m: ([38;5;241m.5[39m, [38;5;241m.5[39m)}
[1;32m     15[0m nx[38;5;241m.[39mdraw_networkx(G, with_labels[38;5;241m=[39m[38;5;28;01mTrue[39;00m, node_color[38;5;241m=[39m[38;5;124m"[39m[38;5;124mtab:purple[39m[38;5;124m"[39m, pos[38;5;241m=[39mpos,
[1;32m     16[0m                 font_size[38;5;241m=[39m[38;5;241m10[39m, font_color[38;5;241m=[39m[38;5;124m"[39m[38;5;124mwhitesmoke[39m[38;5;124m"[39m, arrows[38;5;241m=[39m[38;5;28;01mFalse[39;00m, edge_color[38;5;241m=[39m[38;5;124m"[39m[38;5;124mblack[39m[38;5;124m"[39m,
[1;32m     17[0m                 width[38;5;241m=[39m[38;5;241m1[39m)
[0;32m---> 18[0m A [38;5;241m=[39m np[38;5;241m.[39masarray([43mnx[49m[38;5;241;43m.[39;49m[43mto_numpy_matrix[49m(G))

[0;31mAttributeError[0m: module 'networkx' has no attribute 'to_numpy_matrix'
AttributeError: module 'networkx' has no attribute 'to_numpy_matrix'

