Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
class FeatureScaler(BaseEstimator, TransformerMixin):
    def __init__(self):
        return
    
    def fit(self, X):
        return self
    
    def transform(self, X):
        print("Scaling edge-weights...")
        A_scaled = gp.utils.pass_to_ranks(X)
        return (A_scaled)
    
feature_scaler = FeatureScaler()
A_cleaned_scaled = feature_scaler.transform(A_clean)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[13], line 14[0m
[1;32m     11[0m         [38;5;28;01mreturn[39;00m (A_scaled)
[1;32m     13[0m feature_scaler [38;5;241m=[39m FeatureScaler()
[0;32m---> 14[0m A_cleaned_scaled [38;5;241m=[39m [43mfeature_scaler[49m[38;5;241;43m.[39;49m[43mtransform[49m[43m([49m[43mA_clean[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/sklearn/utils/_set_output.py:142[0m, in [0;36m_wrap_method_output.<locals>.wrapped[0;34m(self, X, *args, **kwargs)[0m
[1;32m    140[0m [38;5;129m@wraps[39m(f)
[1;32m    141[0m [38;5;28;01mdef[39;00m [38;5;21mwrapped[39m([38;5;28mself[39m, X, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[0;32m--> 142[0m     data_to_wrap [38;5;241m=[39m [43mf[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mX[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    143[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(data_to_wrap, [38;5;28mtuple[39m):
[1;32m    144[0m         [38;5;66;03m# only wrap the first output for cross decomposition[39;00m
[1;32m    145[0m         [38;5;28;01mreturn[39;00m (
[1;32m    146[0m             _wrap_data_with_container(method, data_to_wrap[[38;5;241m0[39m], X, [38;5;28mself[39m),
[1;32m    147[0m             [38;5;241m*[39mdata_to_wrap[[38;5;241m1[39m:],
[1;32m    148[0m         )

Cell [0;32mIn[13], line 10[0m, in [0;36mFeatureScaler.transform[0;34m(self, X)[0m
[1;32m      8[0m [38;5;28;01mdef[39;00m [38;5;21mtransform[39m([38;5;28mself[39m, X):
[1;32m      9[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mScaling edge-weights...[39m[38;5;124m"[39m)
[0;32m---> 10[0m     A_scaled [38;5;241m=[39m [43mgp[49m[38;5;241m.[39mutils[38;5;241m.[39mpass_to_ranks(X)
[1;32m     11[0m     [38;5;28;01mreturn[39;00m (A_scaled)

[0;31mNameError[0m: name 'gp' is not defined
NameError: name 'gp' is not defined

