Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Generate a network from an SBM
B = np.array([[0.02, 0.044, .002, .009], 
              [0.044, 0.115, .010, .042],
              [.002, .010, .020, .045],
              [.009, .042, .045, .117]])
n = [100, 100, 100, 100]
A, labels = sbm(n=n, p=B, return_labels=True)

# Instantiate an ASE model and find the embedding
ase = ASE(n_components=2)
embedding_ase = ase.fit_transform(A)

# LSE
lse = LSE(n_components=2)
embedding_lse = lse.fit_transform(A)

# plot
from graphbook_code import draw_layout_plot

fig, axs = plt.subplots(1, 2, figsize=(10, 5))
plot_latents(embedding_ase, labels=labels, ax=axs[0],
             title="Adjacency Spectral Embedding");
plot_latents(embedding_lse, labels=labels, ax=axs[1],
             title="Laplacian Spectral Embedding");
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_2635/3718864610.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# Generate a network from an SBM[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m B = np.array([[0.02, 0.044, .002, .009], 
[0m[1;32m      3[0m               [0;34m[[0m[0;36m0.044[0m[0;34m,[0m [0;36m0.115[0m[0;34m,[0m [0;36m.010[0m[0;34m,[0m [0;36m.042[0m[0;34m][0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m               [0;34m[[0m[0;36m.002[0m[0;34m,[0m [0;36m.010[0m[0;34m,[0m [0;36m.020[0m[0;34m,[0m [0;36m.045[0m[0;34m][0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m               [.009, .042, .045, .117]])

[0;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

